### ISSUE TITLE
"Seeking Help" section in docs

### ISSUE THREAD

**Issue by shivupa** [flatironinstitute/solid_dmft#20]
### Summary
Part of Review: https://github.com/openjournals/joss-reviews/issues/4623

The "How to contribute" is great, and could a "Seeking Help" section be added to the docs? 

### Motivation

This would make it easier if users encounter issues. 

### Implementation
I'd expect this to point at the tutorials/examples, to link to the Github Discussions page, and possibly link to opening an issue.

**Comment by the-hampel** [comment]
Hi @shivupa,
thank you for your feedback. We incorporated your suggestions in commit 62fb3e397bd2516e09070d2abd5ae3167bb63a4a and the changes are online: https://triqs.github.io/solid_dmft/issues.html . We decided to slightly rename the section to `Support & contribute` and then add a subsection `seeking help` . We also revised the text to point to the github discussion page, issues, and the tutorials.

**Comment by shivupa** [comment]
Excellent thanks! Closing as completed
