### ISSUE TITLE
Review suggestion: Build script block at end of building from source section

### ISSUE THREAD

**Issue by shivupa** [flatironinstitute/solid_dmft#21]
### Summary
[Part of Joss Review](https://github.com/openjournals/joss-reviews/issues/4623)

This tool fits very nicely within the Triqs ecosystem and its existence makes sense/does not seem redundant. The installation of solid-dmft follows a similar flow as the other tools within the ecosystem, which is nice from a user's perspective. One thing that would help slightly is a collected build script for the build from source at the end of the installation from source section. [Triqs](https://triqs.github.io/triqs/latest/install.html#compiling-triqs-from-source-advanced) has one in the installation instructions which is little more than a collection of the instructions that preceed it, but it makes copy+pasting easier.

**Comment by the-hampel** [comment]
Hi @shivupa,
we followed your advice and made a copy/paste friendly version of the install instructions: https://triqs.github.io/solid_dmft/install.html . We also link to the docker files, which hold also full installation scripts in an extra section. 
Best,
Alex

**Comment by shivupa** [comment]
Nice happy to see the dockerfiles as well!
