### ISSUE TITLE
Review Suggestion: Can tutorial folder be moved outside of doc/

### ISSUE THREAD

**Issue by shivupa** [flatironinstitute/solid_dmft#22]
### Summary
Tutorial files are in the docs folder which is confusing.

### Motivation

The tutorials were hard to find and the text in the online docs refer to things in those folders.

### Implementation
I believe all that will need changed is the paths in `tutorials.rst`
```
.. _tutorials:

Tutorials
==========

These tutorials provide an overview about typical workflows to perform DFT+DMFT calculations with solid_dmft. The tutorials are sorted by complexity and introduce one after another more available features. 

.. note::
   The tutorials are run with the 3.1.x branch of triqs. Please use the 3.1.x branch for triqs and all applications to reproduce the results shown here. 

Short description of the tutorials linked below: 

1. Typical one-shot (OS) DMFT calculation based on prepared hdf5 archive for SrVO3
2. Full charge self-consistent (CSC) DFT+DMFT calculation using the PLO formalism with Vasp for PrNiO3
3. Full CSC DFT+DMFT calculation using w90 in combination with Quantum Espresso utilizing the lighter HubbardI solver
4. OS magnetic DMFT calculation for NdNiO2 in a large energy window for 5 d orbitals
5. Postprocessing: plot the spectral function after a DFT+DMFT calculation

----

.. toctree::
    :maxdepth: 2

    ../tutorials/SVO_os_qe/tutorial
    ../tutorials/PrNiO3_csc_vasp_plo_cthyb/tutorial
    ../tutorials/Ce2O3_csc_w90/tutorial
    ../tutorials/NNO_os_plo_mag/tutorial
    ../tutorials/correlated_bandstructure/plot_correlated_bands

```

**Comment by the-hampel** [comment]
Hi @shivupa,
thank you for your suggestion. We discussed this and decided against moving the tutorials outside the doc folder. We faced the problem, that sphinx, which we use to build the documentation, searches by default one directory, and has problems if we move the folder outside (this could eventually be fixed but we would like avoid extra modifications). However, we totally understand your point that the tutorials are maybe hard to find on the github page itself. Hence, we changed the README.md file shown on the landing page of github: https://github.com/TRIQS/solid_dmft/tree/unstable . The readme has a new section `Documentation & tutorials` linking to the relevant documentation pages. We hope this satisfies your request sufficiently. Once we agree on this we will merge the unstable readme.md file into the current stable branch.

Best, 
Alex

**Comment by shivupa** [comment]
This seems like a reasonable compromise. I'd also consider also adding a note to https://triqs.github.io/solid_dmft/tutorials.html saying something along the lines of `Note: The files needed to follow along with this tutorial are available in the repository under [PATH to solid_dmft]/doc/tutorials/` just so the files are easier to find. 

I think I will close this now though
