### ISSUE TITLE
Specifying dft_mu leads to wrong DC leads to wrong results

### ISSUE THREAD

**Issue by phibeck** [flatironinstitute/solid_dmft#35]
### Description

When `dft_mu` is given, the DC is calculated based on the corresponding impurity occupations that may be wrong. While the occupations are fixed with a call of `calc_mu` before the DMFT loop, the DC is set and changes the results.

In my opinion, `dft_mu` is helpful to look at the original occupations etc, but it should be corrected before determining the DC. For a single impurity it doesn't change anything, but for multiple ones it affects the results.

**Comment by the-hampel** [comment]
I addressed this in 751c88a335c12213b26fb3610caf534c2751aeee but we can discuss if we want to completely remove this option. I still think it might be useful to have in cases where the chemical potential is far away from 0.0 when starting DMFT.

**Comment by merkelm** [comment]
With this new commit, the behavior looks good to me and I agree that it might be useful. My only suggestion would be to rename the tag to initial_guess_dft_mu or something similar.

**Comment by the-hampel** [comment]
Okay sounds like a plan. What about naming it simply `mu_initial_guess` ?

**Comment by phibeck** [comment]
Sounds good to me.

**Comment by the-hampel** [comment]
fixed in 69f2cf55aaab727f25d31ae99f656102b20d7f74
