### ISSUE TITLE
tomllib.TOMLDecodeError: Expected newline or end of document after a statement

### ISSUE THREAD

**Issue by Vahid999** [flatironinstitute/solid_dmft#90]
Following the Ce2O3_csc_w90 example, I prepared the input files and ran the following script

`#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --time=0:30:00          
#SBATCH --mem=200G
#SBATCH --job-name=triqs
#SBATCH --account=rrg-maassenj

cd $SLURM_SUBMIT_DIR

module load quantumespresso/7.3.1 triqs/3.3.1

mpirun solid_dmft > dmft.out`

The dmft_config.toml file is

`[general]
seedname = "Ca2N"
jobname = "b10-U6.46-J0.46"
csc = true

eta = 0.5
n_iw = 100
n_tau = 5001

n_iter_dmft_first = 2
n_iter_dmft_per = 1
n_iter_dmft = 5

block_threshold = 1e-03

h_int_type = "density_density"
U = 6.46
J = 0.46
beta = 10
prec_mu = 0.1

sigma_mix = 1.0
g0_mix = 1.0
dc_type = 0
dc = true
dc_dmft = true
calc_energies = true

h5_save_freq = 1

[solver]
type = "hubbardI"
n_l = 15
store_solver = false
measure_G_l = false
measure_density_matrix = true

[dft]
dft_code = "qe"
n_cores = 64
mpi_env = "openmpi"
projector_type = "w90"
dft_exec = "pw.x"
w90_tolerance = 1.e-1`

I get the following error:

`Starting run with 64 MPI rank(s) at : 2024-12-06 12:35:22.784716
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/MPI/gcc12/openmpi4/triqs/3.3.1/bin/solid_dmft", line 45, in <module>
    run_solid_dmft.main(sys.argv)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/main.py", line 148, in main
    params = tomllib.load(file)
             ^^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/lib/python3.11/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/lib/python3.11/tomllib/_parser.py", line 127, in loads
    raise suffixed_err(
tomllib.TOMLDecodeError: Expected newline or end of document after a statement (at line 44, column 18)`

Is this a bug or an error on my part?

Thanks,
Vahid

**Comment by Vahid999** [comment]
To update, the dmft_config.toml I used was taken from the Ce2O3 tutorial and did not start running because of two issues:

1. The "store_solver = false" should move to the [general] section
2. I replaced w90_tolerance = 1.e-1 with w90_tolerance = 1e-1. The error I reported above was caused by this "point".

Hopefully there will not be any other runtime issues.

Vahid

**Comment by phibeck** [comment]
Hi @Vahid999,

thanks for reporting this. Indeed, the tutorials were made before we updated the config reader, and the errors you saw resulted from that transition. Thanks for reporting the corrections, we will update the tutorials shortly to reflect that.
