### ISSUE TITLE
solid_dmft for QE gives no output for scf

### ISSUE THREAD

**Issue by Vahid999** [flatironinstitute/solid_dmft#93]
I reported this to the Triqs Gitub forum (issue $975) and maybe it was the wrong place to report it.  The following dmft_config.toml is used

`[general]
seedname = "Ca2N"
jobname = "triqs"
csc = true

eta = 0.5
n_iw = 100
n_tau = 5001

n_iter_dmft_first = 2
n_iter_dmft_per = 1
n_iter_dmft = 5

block_threshold = 1e-03

h_int_type = "density_density"
U = 6.46
J = 0.46
beta = 10
prec_mu = 0.1

sigma_mix = 1.0
g0_mix = 1.0
dc_type = 0
dc = true
dc_dmft = true
calc_energies = true

h5_save_freq = 1

store_solver = false
enforce_off_diag = false
h_int_basis = "qe"

[solver]
type = "hubbardI"
n_l = 15
measure_G_l = false
measure_density_matrix = true

[dft]
dft_code = "qe"
n_cores = 64
mpi_env = "openmpi"
projector_type = "w90"
dft_exec = "pw.x"
w90_tolerance = 1e-1`

My submission script on ComputeCanada is

`#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --time=1:0:00
#SBATCH --mem=200G
#SBATCH --job-name=triqs

cd $SLURM_SUBMIT_DIR

module load quantumespresso/7.3.1 triqs/3.3.1

set path = './ref/'

mpirun solid_dmft > dmft.out `

The files Ca2N.scf.out and Ca2N.scf.err are created but empty.

The dmft.out file shows the following (plus all the settings):

solid_dmft: Running QE...
solid_dmft: Starting scf calculation...

Is this an error on my part or a bug?

Thanks,
Vahid

**Comment by phibeck** [comment]
Hi @Vahid999,

this is just due to the fact that we launch the QE run via a subprocess, which means that the output is written to file only after the process has finished. Once solid_dmft reports that the scf calculation has finished (it does this by moving on to bands/nscf calculation) you should see the output in Ca2N.scf.out.

If it takes a long time you can start with fewer k-points and check that the calculation works as intended, but in principle you will just have to wait for QE to finish.

Best,
Sophie

**Comment by Vahid999** [comment]
Hi Sophie,

Some good and some bad news! I waited for more than 10 hours and the scf did not finish. Outside Triqs, the scf finishes in 6 minutes. After a few trials, I managed to get Triqs to finish the scf and nscf by adding the following line to the submission scripts:

#SBATCH --ntasks-per-core=1

However, after finishing nscf, Triqs started the wannier90 job and crashed with the following error:

At line 98 of file ../wannier_prog.F90 (unit = 10, file = 'Ca2N.werr')
Fortran runtime error: File cannot be deleted

Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/bin/solid_dmft", line 45, in <module>
    run_solid_dmft.main(sys.argv)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/main.py", line 151, in main
    run_dmft(params, config_file_name)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/main.py", line 95, in run_dmft
    csc_flow_control(general_params, solver_params, dft_params, gw_params, advanced_params)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/csc_flow.py", line 277, in csc_flow_control
    _full_qe_run(general_params['seedname'], dft_params, 'initial')
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/csc_flow.py", line 119, in _full_qe_run
    qe_wrapper('win_pp')
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/csc_flow.py", line 100, in <lambda>
    qe_wrapper = lambda calc_type: qe.run(dft_params['n_cores'], calc_type, dft_params['dft_exec'],
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/dft_managers/qe_manager.py", line 130, in run
    _start_with_piping(mpi_exe, arguments, qe_file_ext, env_vars, seedname)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/MPI/gcc12/openmpi4/triqs/3.3.1/lib/python3.11/site-packages/solid_dmft/dft_managers/qe_manager.py", line 82, in _start_with_piping
    subprocess.check_call(mpi_arguments + [seedname], env=env_vars, shell=False)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcccore/python/3.11.5/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcc12/openmpi/4.1.5/bin/mpirun', '-hostfile', 'dft.hostfile', '-np', '40', '-mca', 'mtl', '^psm,psm2,ofi', '-mca', 'btl', '^vader,openib,usnix', '-x', 'LD_LIBRARY_PATH', '-x', 'PATH', '-x', 'OMP_NUM_THREADS', 'wannier90.x', '-pp', 'Ca2N']' returned non-zero exit status 2.

The Ca2N.wout stops at the following line:

 *------------------------------- WANNIERISE ---------------------------------*
 |  Total number of iterations                     :              2000             |
 |  Number of CG steps before reset         :                 5               |
 |  Trial step length for line search             :             2.000            |
 |  Convergence tolerence                        :         0.100E-09        |
 |  Convergence window                           :                -1             |
 |  Iterations between writing output          :                 1             |
 |  Iterations between backing up to disk     :               100         |

Would you happen to know what might be causing this error?

Thanks,
Vahid


On Dec 16, 2024, at 4:02 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi @Vahid999<https://github.com/Vahid999>,

this is just due to the fact that we launch the QE run via a subprocess, which means that the output is written to file only after the process has finished. Once solid_dmft reports that the scf calculation has finished (it does this by moving on to bands/nscf calculation) you should see the output in Ca2N.scf.out.

If it takes a long time you can start with fewer k-points and check that the calculation works as intended, but in principle you will just have to wait for QE to finish.

Best,
Sophie

**Comment by Vahid999** [comment]
Hi Sophie,

I just saw that the same error was reported in #29 of the Discussions section. It has to do with parallelizing the Wannier code. I will give that solution a try. Hopefully, it will resolve the issue.

Regards,
Vahid

**Comment by Vahid999** [comment]
Indeed the error is due to the wannier90.x not having been compiled for parallel execution. Now the solid_dmft code works as it should. Now I need to figure out all the proper settings in the .toml file.

Vahid
